ONSETS = ['B',
        'B L',
        'B R',
        'B Y',
        'CH',
        'D',
        'D R',
        'DH',
        'F',
        'F L',
        'F R',
        'F Y',
        'G',
        'G L',
        'G R',
        'G W',
        'G Y',
        'HH',
        'HH Y',
        'JH',
        'K',
        'K L',
        'K R',
        'K W',
        'K Y',
        'L',
        'M',
        'M Y',
        'N',
        'P',
        'P L',
        'P R',
        'P Y',
        'R',
        'S',
        'S K',
        'S K L',
        'S K R',
        'S K W',
        'S K Y',
        'S L',
        'S M',
        'S N',
        'S P',
        'S P L',
        'S P R',
        'S P Y',
        'S T',
        'S T R',
        'S W',
        'SH',
        'SH R',
        'T',
        'T R',
        'T W',
        'TH',
        'TH R',
        'TH W',
        'V',
        'V Y',
        'W',
        'Y',
        'Z',
        'ZH']

VOWELS = ['EY1',
        'AH0',
        'AE1',
        'IY0',
        'AE2',
        'IY1',
        'EY2',
        'IY2',
        'IH0',
        'OW1',
        'AA1',
        'AH1',
        'EH1',
        'ER0',
        'AO1',
        'AY1',
        'IH1',
        'IH2',
        'ER1',
        'UW0',
        'AY2',
        'OW2',
        'AH2',
        'OY2',
        'OY1',
        'UH2',
        'ER2',
        'UH1',
        'AW2',
        'EY0',
        'EH2',
        'AO2',
        'OW0',
        'AA2',
        'AW1',
        'UW2',
        'UW1']
